#!/usr/bin/bash

sudo pacman -Sy yay \
        aws-cli-v2 \
        binutils \
        brave-browser \
        deno \
        discord \
        docker \
        docker-compose \
        fakeroot \
        fd \
        gcc \
        gimp \
        gnome-themes-extra \
        go \
        go-yq \
        gvim \
        htop \
        i3 \
        iputils \
        jq \
        keepassxc \
        kitty \
        lazygit \
        libpqxx \
        linux66-headers \
        lsof \
        make \
        manjaro-printer \
        mesa \
        mesa-utils \
        mpdecimal \
        neofetch \
        nodejs \
        npm \
        nvm \
        nvtop \
        obs-studio \
        patch \
        pkgconf \
        python-pip \
        python-pipx \
        ripgrep \
        rofi \
        stow \
        telegram-desktop \
        tk \
        ttf-sourcecodepro-nerd \
        v4l2loopback-dkms \
        vlc \
        xclip \
        xorg-xeyes \
        yarn \
        --needed
